# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.hostname = "oshift.local"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, path: "bootstrap.sh"

  # config.vm.box_check_update = false
  #config.vm.network "private_network",ip:"192.168.10.15"
  config.vm.synced_folder "~/", "/vagrant_home"

  config.vm.network "forwarded_port", guest: 8443, host: 8443

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8192"
    vb.cpus = 2
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # bento box bug workaround - https://github.com/chef/bento/issues/688
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

end
